name: flutter_gherkin_integration
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter forked from flutter_gherkin integration_test__package_support branch
version: 0.0.1-rc.1
homepage: https://github.com/PROGrand/flutter_gherkin

environment:
  sdk: '>=2.14.2 <3.0.0'
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ">=1.7.1 <3.0.0"
  collection: ^1.15.0
  gherkin: ^2.0.8
  source_gen: ^1.1.1
  build: ^2.1.1
  glob: ^2.0.2
    # gherkin:
  # path: ../dart_gherkin

dev_dependencies:
  meta: ^1.7.0
  pedantic: ^1.11.1
  build_config: ^1.0.0

flutter:
